Feedback fixes
FAIR2-for-research-software/FAIR4RS-Packaging pull request #25
Opened 2024-08-14 13:47 UTC by christopher-wild

addresses feedback for episodes 2, 3 & 4

closes #17 #18 #19

2024-09-17 11:24 UTC, f-allian commented on episodes/package-file-history.Rmd
>  Introduced in (PEP517)[https://peps.python.org/pep-0517/], the latest file for packaging a python project is the `pyproject.toml` file.
The URL is still not displayed properly.

2024-09-17 11:26 UTC, f-allian commented on episodes/package-file-history.Rmd
> +:::
I think the key points here can be better summarised that align with the episode's questions/learning objectives

2024-09-17 11:29 UTC, f-allian commented on episodes/accessing-packages.md
>  ### Exercise 2: Create venv and install Numpy
The Windows/Mac tabs look absolutely massive here! Might be because of the number of `#`? 

![image](https://github.com/user-attachments/assets/03dda863-e0b6-4548-b56d-224319234603)

2024-09-17 11:31 UTC, f-allian commented on episodes/accessing-packages.md
Again I think the key points below can be made more informative

2024-09-17 11:33 UTC, f-allian requested changes
@christopher-wild Sorry for the delay on this. I've left a few suggestions below.

2024-09-30 10:00 UTC, christopher-wild commented on episodes/accessing-packages.md
>  ### Exercise 2: Create venv and install Numpy
They do look commically big on yours! The amount of `#`'s is the same as the [workbench recommends](https://carpentries.github.io/sandpaper-docs/episodes.html#tab) and looks okay on mine 
![image](https://github.com/user-attachments/assets/fa33202d-3794-45fb-aa67-5a14e0b56eb1).

2024-09-30 10:05 UTC, christopher-wild commented
> @christopher-wild Sorry for the delay on this. I've left a few suggestions below.

Cheers for the helpful feedback, let me know if you think the new keypoints are any better 🙂

2024-10-04 10:01 UTC, f-allian commented on episodes/accessing-packages.md
>  ### Exercise 2: Create venv and install Numpy
@christopher-wild that's strange! Never mind then!

2024-10-04 10:06 UTC, f-allian approved these changes
Looks great thanks @christopher-wild!

2025-03-31 13:57 UTC, merged